apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-2-
  annotations:
    kueue.x-k8s.io/queue-name: on-demand-lq
spec:
  ttlSecondsAfterFinished: 60
  parallelism: 5
  completions: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: bash:5
        command: ["sleep"]
        args: ["5"]
        resources:
          requests:
            memory: "600Mi"
  backoffLimit: 0