apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "spot-lq"
spec:
  clusterQueue: "spot-cq"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "on-demand-lq"
spec:
  clusterQueue: "on-demand-cq"